# Generated by Django 4.2.30 on 2026-06-01 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_on_temp_high', models.BooleanField(default=True)),
                ('temp_high_threshold', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('alert_on_temp_low', models.BooleanField(default=False)),
                ('temp_low_threshold', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('alert_on_wind_high', models.BooleanField(default=True)),
                ('wind_high_threshold', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('alert_on_storm', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='weather.savedlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
